name: "\ud83d\udc1b Bug report"
description: "Something isn't working as expected"
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What did you expect to happen and what actually happened?
      placeholder: "A clear and concise description of the problem..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please describe how we can reproduce the issue
      placeholder: "1. Setup...\n2. Call method...\n3. Error..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: "e.g. 1.0.0"
    validations:
      required: true
