name: "ðŸ› Bug report"
description: "Report an unexpected behavior or a failure."
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the following details."

  - type: textarea
    id: description
    attributes:
      label: "What happened?"
      description: "Describe the bug in detail. What did you expect to happen?"
      placeholder: "The setting didn't persist after saving..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Provide steps to reproduce the issue."
      placeholder: "1. Call setting()->for($user)->set(...)
2. Refresh the page
3. See incorrect behavior"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Package version"
      placeholder: "e.g., v1.0.2"

  - type: dropdown
    id: scope
    attributes:
      label: "Which scope did the issue occur in?"
      options:
        - Global (default)
        - User
        - Team
        - Other