blank_issues_enabled: false

#contact_links:
#  - name: Discussions & Community Support
#    url: https://github.com/danielemontecchi/laravel-scoped-settings/discussions
#    about: Please use Discussions for general questions or help.
