name: "📚 Documentation issue"
description: "Report something missing or unclear in the docs."
title: "[Docs] "
labels: ["type:docs"]
body:
  - type: textarea
    id: where
    attributes:
      label: "Where is the documentation unclear or missing?"
      placeholder: "e.g., in usage.md > set() example"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: "What could be improved?"
      placeholder: "It would help to add a code snippet showing..."
    validations:
      required: true