name: "✨ Feature request"
description: "Propose a new feature or capability."
title: "[Feature] "
labels: ["type:feature"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: "What problem would this solve?"
      description: "Explain the use case or pain point."
      placeholder: "I need to define default settings per group..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Describe the solution you'd like"
      placeholder: "Add support for group-level scoping with fallback to team..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Any alternative solutions or workarounds?"
      placeholder: "I currently work around it by..."