name: "\ud83d\udca1 Feature request"
description: "Suggest an idea or enhancement"
title: "[Feature] "
labels: ["type:feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: What feature would you like to see?
      description: Describe your idea and how it would improve the package
      placeholder: "I’d like to be able to..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature useful?
      description: Explain the use case or problem this feature would solve
      placeholder: "This would help when..."
    validations:
      required: false
