name: "❓ Usage question"
description: "Ask a question about how to use the package."
title: "[Question] "
labels: ["type:question"]
body:
  - type: textarea
    id: context
    attributes:
      label: "What are you trying to do?"
      placeholder: "I'm trying to override a setting only if the team has one defined..."
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: "Relevant code snippet"
      placeholder: "Add any relevant code, if needed."