name: Deploy versioned documentation

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # necessario per accedere a tutti i tag

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs==1.6.1 mkdocs-material==9.5.15 mike==2.1.3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Deploy documentation
        run: bash ./prepare-docs.sh
