name: ♻️ Sync GitHub Labels

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/labels.yml"

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: 📅 Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: ♻️ Create or update labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}