name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
        laravel: ['10.*', '11.*', '12.*', '13.*']
        exclude:
          - php: '8.1'
            laravel: '13.*'
          - php: '8.3'
            laravel: '10.*'

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up PHP
        uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2, pest

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer install --prefer-dist --no-progress

      - name: Run tests
        run: ./vendor/bin/pest

      - name: Run linting
        run: composer lint

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up PHP
        uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer:v2, pest

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests with coverage
        run: ./vendor/bin/pest --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a605bd92782ce0810fa3b8acc235c921b497052
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: danielemontecchi/laravel-scoped-settings